### ISSUE TITLE
2 Questions about Parsing

### ISSUE THREAD

**Issue by Axiomatic-Mind** [shnewto/bnf#105]
1. Why does `Grammar::parse_input` have a return type of `impl Iterator<Item = ParseTree>` and not of `Option<ParseTree>` or `Result<ParseTree, Error>`? Is there any circumstance in which `Grammar::parse_input` could parse to multiple `ParseTree`s?

2. I know that I can access the data in a `ParseTree` by calling `ParseTree::rhs_iter` to get something of type `ParseTreeIter`, which implements `Iterator<Item = &ParseTreeNode>`. I can then iterate through this to get items of type `&ParseTreeNode`, but how can I get the data out from this? `src/lib.rs` only publicly exports `Grammar` and `ParseTree` from `src/grammar.rs`, and I cannot construct the variants of the externally private `ParseTreeNode` necessary to match `ParseTreeNode`s and access the data stored within.

**Comment by shnewto** [comment]
Hey @Axiomatic-Mind 👋 as to your first question, whether `parse_input` returns a list of parse trees or not is mostly up to your grammar, and things like grammars for programming languages usually shouldn't have ambiguous ways to interpret a sentence. But grammars for natural language can be full ambiguities that can lead to multiple parse tree. My personal favorite example of the kind of sentence that would lead a parser like this to return multiple trees is "Time flies like an arrow". Where we're either talking about the concept of time moving quickly, _or_ something more like a plot line from Doctor Who, i.e. "Time flies like an arrow. Fruit flies like a banana."

As to your second question, it's a great point! ParseTreeNode probably needs to be exposed!

**Comment by Axiomatic-Mind** [comment]
Thanks! Embarrassingly, I was trying to get that information by calling `format!(“{:?}”, foo)` on the output of the `parse_input` function and using regular expressions to parse it. The lengths to which one will go!

**Comment by shnewto** [comment]
Thanks so much for #106! I've published version 0.4.1 to crates.io now so you should be able to use your changes

**Comment by CrockAgile** [comment]
Thanks for noticing this issue @Axiomatic-Mind ! totally just an oversight. And double thanks for opening a PR 🙌

**Comment by Axiomatic-Mind** [comment]
My pleasure👍
