### ISSUE TITLE
Operator Traits

### ISSUE THREAD

**Issue by CrockAgile** [shnewto/bnf#34]
[`core::ops`](https://doc.rust-lang.org/core/ops/) allows implementing custom logic for operators. Would implementing these for `Grammar`/`Production`/`Expression`/`Term` enable any cleaner syntax or usage? If so, which of these operators would be included?

- [ops::Add (+)](https://doc.rust-lang.org/core/ops/trait.Add.html)
  - Would this add same types (Grammar + Grammar -> Grammar)?
  - Would this add a component (Grammar + Production -> Grammar)?
  - Would this add components (Production + Production -> Grammar)?
  - Would this do all the above?
  - If this is implemented, what is the behavior or subtraction?
- [ops::AddAssign (+=)](https://doc.rust-lang.org/core/ops/trait.AddAssign.html)
  - Same question as Add
- [ops::BitOr ( | )](https://doc.rust-lang.org/core/ops/trait.BitOr.html)
  - If Add is used only for components, could Or be used as a kind of union operator?
  - Should this only be implemented for Term | Term and Term | Expression to allow `expr = Term | Term | Term`?
- [ops::BitXor ( ^ )](https://doc.rust-lang.org/core/ops/trait.BitXor.html)
  - If BitOr is used as a union operator, should BitXor be used for set difference?

These were the operators I identified as possible enhancements, but feel free to add more to the discussion that may be useful.

Also, as a possible alternative some of these use cases could be handled by macros to allow for special case syntax:

 `expression![ term1 | term2 | term3 ] -> Expression::from_parts(vec![ term1, term2, term3 ])`

But that would require the user importing BNF's macros.

**Comment by snewt** [comment]
@CrockAgile I think custom operators represents a huge add. `+`, `+=`, and `|` seem like intuitive targets but I'm glad you brought up `-` and `^`. I hadn't really thought of them but they make sense.

**Comment by CrockAgile** [comment]
I am gonna close this issue. I think the most intuitive operator has already been added (thank you @DrunkJon!), and the rest require more discussion and demand from users.

I'm happy to re-open this tho, if anyone feels interested in taking it farther

**Comment by shnewto** [comment]
Same page, thanks @CrockAgile!
