### ISSUE TITLE
Step by step example

### ISSUE THREAD

**Issue by sergeyklay** [shnewto/bnf#38]
Hello,

First of all wanted to say thank you for your hard work on this project.

What do you think about creating step by step example with using simple grammar? It seems to me this would help to see the usual work flow and may show general concepts better.

FYI: There is a template to make a good README.md https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by snewt** [comment]
@sergeyklay I think that's a great idea, and I believe it represents a valuable addition. It's a really clean template too, I'll plan on incorporating some of it's style. Thank you for raising the issue!

**Comment by snewt** [comment]
FYI, I'm working on a feature addition related to #33 that I'd like to have incorporated in the next week or so. I'll plan on making this part of the changes to the documentation that issue will require.

**Comment by snewt** [comment]
Hey @sergeyklay , just checking in to say I haven't forgotten about this! I'm unsure what the timeline for this issue looks like at the moment but I thought I'd poll you for a little more info. Maybe you could provide an example of what a simple example might illustrate? 

Some initial thoughts were examples that could do the following:
- Traverse a `Grammar` data structure using iterators.
- Build a `Grammar` data structure without an input `String`.
- Read an input grammar from a file and use it to generate a `Grammar` data structure.

Would any of these options illustrate what you're interested in? What else would be valuable in terms of step-by-step examples? 

Thanks!

**Comment by sergeyklay** [comment]
Hello @snewt,

I'm from yacc/bison world. In fact, what you described above is very interesting and probably will be enough. I just wanted to show you a few links that were very useful for me:

* [re2c examples](http://re2c.org/examples/examples.html)
* [Quick Tour to LEMON](http://lemon.cs.elte.hu/pub/doc/latest-svn/quicktour.html)
* [Five minute introduction to ANTLR 3](https://theantlrguy.atlassian.net/wiki/spaces/ANTLR3/pages/2687102/Five+minute+introduction+to+ANTLR+3)
* [Quick Starter on Parser Grammars](https://theantlrguy.atlassian.net/wiki/spaces/ANTLR3/pages/2687210/Quick+Starter+on+Parser+Grammars+-+No+Past+Experience+Required)

**Comment by snewt** [comment]
Ah @sergeyklay those are great examples, I'll definitely pull from them for reference. Thank you. I think you'll be interested in the feature I'm working on at the moment (associated with issue #33) that will parse an input using a predefined `Grammar` to generate an AST or something like it (if the input is valid according to that grammar and report errors otherwise). That will help us make the leap to something more useful in terms of a corollary to lex/flex and yacc/bison.

**Comment by CrockAgile** [comment]
do you think the README has caught up to this issue? or what is still missing?

**Comment by shnewto** [comment]
I agree @CrockAgile

**Comment by CrockAgile** [comment]
Okay! then I am gonna close, but happy to re-open if anything else is needed
