### ISSUE TITLE
suggestion: extract bnf test-cases to their own .bnf files?

### ISSUE THREAD

**Issue by SKalt** [shnewto/bnf#79]
What would you think of extracting the test-cases to separate files and then re-including them using [`std::include_str!("path/to/file")`](https://doc.rust-lang.org/std/macro.include_str.html)?

Potential benefits might include
- increased ease of reuse of test cases in this and other projects
- no need for string-in-string escaping, extra indentation to make the strings look right 

This'd come at the cost of separating the text of the test-cases from the expected result.

**Comment by shnewto** [comment]
Yeah totally agree, there's a lot of reasons that's much a better solution. Fully support it.

**Comment by CrockAgile** [comment]
closed by #80 ?

**Comment by shnewto** [comment]
Ah yep looks like it is, closing 👍
